version: '3.7'

services:
  api:
    build:
      context: ./
    image: pdfservice
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./data:/data
      - ./app:/app

  rabbitmq:
    image: rabbitmq:latest
    expose:
      - 5672
    ports:
      - 5672:5672

  workers:
    image: pdfservice
    # Limit processes and thread for local o handle it. Should be tweaked for production or added more workers.
    entrypoint: dramatiq worker --processes 1 --threads 4
    volumes:
      - ./data:/data
      - ./app:/app
    depends_on:
      - api
      - rabbitmq

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pdf
    expose:
      - 5432
    ports:
      - "54320:5432"

  redis:
    image: redis:7.0.0-alpine3.15
    # No persistence for local development. For production this should be treated as pet, not cattle.
    command: redis-server --save "" --appendonly no

volumes:
  postgres_data:
