version: '3.7'

services:
  app:
    build: .
    command: python app.py
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pdf
    expose:
      - 5432
    ports:
      - "54320:5432"

volumes:
  postgres_data:
