version: '3.7'

services:
  api:
    build:
      context: ./
    image: pdfservice
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./data:/data
      - ./app:/app
    restart: on-failure

  rabbitmq:
    image: rabbitmq:latest
    expose:
      - 5672
    restart: on-failure

  workers:
    image: pdfservice
    entrypoint: dramatiq worker --watch .
    restart: on-failure
    volumes:
      - ./data:/data
      - ./app:/app
    depends_on:
      - api
      - rabbitmq

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pdf
    expose:
      - 5432
    ports:
      - "54320:5432"

volumes:
  postgres_data:
